---
- hosts: agent
  gather_facts: False
  tasks:
    - name: kill agent_client
      shell: pkill -f agent_client
      ignore_errors: True      
      
    - name: execute run script
      shell: ./run.sh chdir=/root/sodero/agent
